import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mijn Straat Jouw Straat - Houd Nederland schoon!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-black to-stone-900">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <img src='./images/mijn-straat-jouw-straat-logo-oranje-wit.svg' alt="Mijn Straat Jouw Straat" className="w-64" />
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div
              className="flex max-w-xs flex-col gap-4 rounded-xl p-8 text-white bg-white/20"
            >
              <h3 className="text-4xl font-bold">Straat vies?</h3>
              <div className="text-lg">
                Meld het met behulp van onze app en help mee om jouw straat schoon te houden! Zelf schoonmaken hoeft niet! (wel fijn natuurlijk...)
              </div>
            </div>
            <div
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-8 text-white"
            >
              <h3 className="text-4xl font-bold">Download de app</h3>
              <div className="text-lg">
                Download de app voor Android of iOS en meld jouw straat schoon!

                <p className="mt-4">
                  Beschikbaar vanaf 1 juli 2023.
                </p>
              </div>
            </div>
          </div>

          <div className="flex flex-row gap-2">
            <img src='./images/google-play-store.svg' alt="Download in Google Play" className="w-40" />
            <img src='./images/apple-app-store.svg' alt="Download in Apple App Store" className="w-40" />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
